name: currency
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: 0.10.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: 2.0.7
  dio: ^5.8.0
  intl: ^0.18.1
  syncfusion_flutter_datagrid: ^23.1.40
  syncfusion_flutter_datepicker: ^23.1.40
  flutter_svg: ^2.0.7
  flutter_dotenv: ^5.1.0
  lottie: 
  flutter_launcher_icons: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_icons:
  image_path: "assets/images/cover.jpg"
  android: "launcher_icon"
  ios: true 
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: amiri
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 900
    - family: MulishRoman
      fonts:
        - asset: assets/fonts/MulishRomanBold.ttf
          weight: 700